# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{railslove-rack-throttle}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Arto Bendiken", "Brendon Murphy", "reddavis"]
  s.date = %q{2010-07-15}
  s.description = %q{Rack middleware for rate-limiting incoming HTTP requests.}
  s.email = %q{reddavis@gmail.com}
  s.extra_rdoc_files = [
    "README",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     ".yardopts",
     "AUTHORS",
     "README",
     "README.md",
     "Rakefile",
     "UNLICENSE",
     "VERSION",
     "doc/.gitignore",
     "etc/gdbm.ru",
     "etc/hash.ru",
     "etc/memcache-client.ru",
     "etc/memcache.ru",
     "etc/memcached.ru",
     "etc/redis.ru",
     "lib/rack/throttle.rb",
     "lib/rack/throttle/daily.rb",
     "lib/rack/throttle/hourly.rb",
     "lib/rack/throttle/interval.rb",
     "lib/rack/throttle/limiter.rb",
     "lib/rack/throttle/per_minute.rb",
     "lib/rack/throttle/time_window.rb",
     "lib/rack/throttle/version.rb",
     "railslove-rack-throttle.gemspec",
     "spec/daily_spec.rb",
     "spec/hourly_spec.rb",
     "spec/interval_spec.rb",
     "spec/limiter_spec.rb",
     "spec/per_minute_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/railslove/rack-throttle}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Extension of rack-throttle - HTTP request rate limiter for Rack applications.}
  s.test_files = [
    "spec/daily_spec.rb",
     "spec/hourly_spec.rb",
     "spec/interval_spec.rb",
     "spec/limiter_spec.rb",
     "spec/per_minute_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<rack-test>, [">= 0.5.3"])
      s.add_runtime_dependency(%q<rack>, [">= 1.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<rack-test>, [">= 0.5.3"])
      s.add_dependency(%q<rack>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<rack-test>, [">= 0.5.3"])
    s.add_dependency(%q<rack>, [">= 1.0.0"])
  end
end

